databases:
  - name: jmp-timetable-generator
    databaseName: jmp_calendar_web_production
    user: jmp_calendar_web
    plan: free

services:
  - type: web
    name: jmp-timetable-generator
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
