default: &default
  region: "ap-southeast-2"
  access_key_id: <%= ENV.fetch("AWS_LAMBDA_ACCESS_KEY") %>
  secret_access_key: <%= ENV.fetch("AWS_LAMBDA_SECRET_KEY") %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
